import { NexusIntegrationTeam } from './nexus-integration-team.model';
import { ProductBacklogItem } from './product-backlog-item.model';
import { Sprint } from './sprint.model';

export interface Project {
  id?: string; // Optional, as it's generated by the backend
  projectName: string;
  description: string;
  startDate: Date;
  endDate: Date;
  nexusIntegrationTeam: NexusIntegrationTeam[];
  nexusGoalId: string; // Reference to the NexusGoal
  productBacklog: ProductBacklogItem[];
  sprints: Sprint[];
}
